name: Validate Repository Structure
# Defines the name of the workflow.

on:
  pull_request:
    branches:
      - main
# Triggers the workflow when a pull request is opened or updated, targeting the 'main' branch.

jobs:
  validate:
    runs-on: ubuntu-latest
# Defines the job named 'validate', which runs on the latest Ubuntu OS.

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
# Step 1: Uses the 'checkout' action to fetch the repository's code.

      - name: Check for README File
        run: |
          if [ -f README.md ]; then
            echo "README file found.";
          else
            echo "README file is missing! Please add one." && exit 1;
          fi
# Step 2: Runs a shell command to check if the 'README.md' file exists in the repository.
# If the file is missing, it exits with an error code (1), which marks the workflow as failed.